### ISSUE TITLE
RequestQuote TODO

### ISSUE THREAD

**Issue by ernie-eunsang** [dobby-in-the-house/main-website#1]
## Now
- [ ] 서버에서 API 제공 (GET and POST: `/request-quote`)
- [ ] 서버에서 기존에 신청한 이메일 내역을 체크해서 있다면 에러 핸들링
- [ ] Sendgrid API를 이용해 고객과 회사에게 각각 메일 발송
- [ ] CSS 작업

## Later
- [ ] ThankYou 페이지는 신청한 이미 신청했던 사람만 접근 (`localStorage` 또는 `action` 활용)
- [ ] RequestQuote 클라이언트 사이트 에러 핸들링 (이메일, 전화번호, 주소(Autocomplete))
- [ ] 인증 기능 구현이 끝나면 `/requested-quote-list`에는 디자이너만 접근할 수 있도록 작업
